id: P7C438F34
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD152291
  title: དཔལ་ལྡན་ས་སྐྱ་པའི་གསུང་རབ་གྲགས་ཆེན་བཅོ་བརྒྱད།
  volumes:
    b21d447cceea4ac787b7a5dc98bc849d:
      image_group_id: I2PD18407
      title: ''
      base_file: v001.txt
    ab5afb54d6b4420f908a6cc1b693c861:
      image_group_id: I2PD18408
      title: ''
      base_file: v002.txt
    20f8b47c3b044441b3ec104085339285:
      image_group_id: I2PD18409
      title: ''
      base_file: v003.txt
    0760441de69f4d1a8a0a353d6af0a536:
      image_group_id: I2PD18410
      title: ''
      base_file: v004.txt
    298d7bf0019a4770bc9338e3474fede4:
      image_group_id: I2PD18411
      title: ''
      base_file: v005.txt
    c9a16d6061d14a5c9afadc2145fbf051:
      image_group_id: I2PD18412
      title: ''
      base_file: v006.txt
    1308989a19324bcb82fd23a5aea8a9ef:
      image_group_id: I2PD18413
      title: ''
      base_file: v007.txt
    2a8807c4c4f843b0b38b38fcf4738fb0:
      image_group_id: I2PD18414
      title: ''
      base_file: v008.txt
    38bfdad268114eecb6c848366c6650ec:
      image_group_id: I2PD18415
      title: ''
      base_file: v009.txt
    19b59521448244e2aad4c0d6761a4578:
      image_group_id: I2PD18416
      title: ''
      base_file: v010.txt
    b1ebac2e98ad46d783c38dd7445a0ad5:
      image_group_id: I2PD18417
      title: ''
      base_file: v011.txt
    68f6c5c3681543ca8012e8c0dd0cdcdd:
      image_group_id: I2PD18418
      title: ''
      base_file: v012.txt
    22c4b7e3c3b7439c9f2b1bd6343f3131:
      image_group_id: I2PD18419
      title: ''
      base_file: v013.txt
    6dd410b9e80e4d8d92cd5d58d988e971:
      image_group_id: I2PD18420
      title: ''
      base_file: v014.txt
    1fcdd84e731b48b8bf88c820378a113a:
      image_group_id: I2PD18421
      title: ''
      base_file: v015.txt
    d5f3a30cff5d401caddbf21172f1ff8f:
      image_group_id: I2PD18422
      title: ''
      base_file: v016.txt
    ea8211baa6354903b433ccf1f94dc5aa:
      image_group_id: I2PD18423
      title: ''
      base_file: v017.txt
    fc62228b929644f9ad77b7ff533cf11a:
      image_group_id: I2PD18424
      title: ''
      base_file: v018.txt
  author: ''
